version: 2.1

jobs:
  build-for-linux:
    docker: 
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: make clean
      - run: make all
      - run: cd bin && ./example1
 build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Installing g++
          command: 'choco install mingw'
      - run:
          name: Compiling Code
          command: 'make all'
      - run:
          name: Running Code
          command: cd bin && ./example1
    
      
 

workflows:
  version: 2.1
  Running JSONSki on Linux:
    jobs:
      - build-for-linux
      - build-for-macos
