version: 2.1

jobs:
  build-for-linux:
    docker: 
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: make clean
      - run: make all
      - run: ls
      - run: cd bin
      - run: ls
      
 

workflows:
  version: 2.1
  build:
    jobs:
      - build-for-linux
