version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-for-linux:
    docker: 
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: make clean
      - run: make all
      - run: cd bin && ./example1
      
  build-for-windows:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: mkdir -p bin ; g++ -O3 -std=c++11 -mavx -mavx2 -msse -msse2 -msse4 -msse4.2 -mpclmul -o bin/example1 src/*.cpp example/example1.cpp -lpthread -mcmodel=medium -static-libstdc++ ; cd bin ; ./example1

workflows:
  version: 2.1
  build:
    jobs:
      - build-for-linux
      - build-for-windows